gooddata/gooddata-js

- src/execution.js
- test/execution_test.js
small fixes to adapt to new MD object model
> RELATED CL-9028 Execute and render column chart

- src/catalogue.js
- test/catalogue_test.js
- test/fixtures/catalogue.js
- when specifying wanted dataSet type (requiredDataSets key)
> FEATURE: CL-9954 Update for unified loadCatalog and loadDateDataSet API

- src/metadata.js
- test/metadata_test.js
getObjectUsing (using2), getObjects (new bulk api)
Related pull-request: https://github.com/gooddata/gdc-dashboards/pull/392/
> RELATED: ONE-115 Extract methods related to bulk dashboard load

- src/execution.js
> RELATED: ONE-1711 Rename dataset to dataSet

- src/execution.js
- test/execution_test.js
Demo: https://client-demo.na.intgdc.com:50020
> RELATED: BB-56 Table column header shortening

- index.d.ts
- src/metadata.js
- test/metadata.test.js
and fixed expect to be called in ok result
> RELATED: RAIL-286 Added metadata visualisation API

- index.d.ts
- src/admin/routes.js
- src/metadata.js
- src/util.js
- test/metadata.test.js
- test/util.test.js
I would like general code review as its my first independent commit ;)
> RELATED: RAIL-286 Added objects query API

- .travis.yml
- index.d.ts
- package.json
- src/catalogue.js
- src/gooddata.js
- test/gooddata.test.js
- yarn.lock
`yarn upgrade gooddata@6.0.0-ocetnik-utils-2018-03-09T09-50-51-168Z`
> RELATED: RAIL-657 Export utils

- src/metadata.js
- test/metadata.test.js
> FEATURE: BB-764 Enable restrictiveDefinitionContent within getValidElements

- src/DataLayer/DataTable.ts
- src/DataLayer/constants/errors.ts
- src/DataLayer/index.ts
`6.0.0-vaclavbohac-remove-error-codes-2018-04-17T13-20-11-264Z`
> RELATED: RAIL-670 Remove redundant HTTP status codes

- src/execution/execute-afm.ts
- test/execution/execute-afm.test.ts
`6.1.1-ocetnik-doc-paging-count-2018-07-12T10-46-28-143Z`
> BUGFIX: RAIL-1044 Fix computing paging count and 1 dimension merging in executeAfm

- src/DataLayer/adapters/ExecuteAfmAdapter.ts
- src/DataLayer/dataSources/DataSource.ts
- src/DataLayer/dataSources/tests/DataSource.spec.ts
- src/DataLayer/interfaces/DataSource.ts
- src/DataLayer/utils/DummyDataSource.ts
- src/execution.ts
- src/execution/execute-afm.ts
- src/execution/experimental-executions.ts
- test/execution/execute-afm.test.ts
`7.1.0-ocetnik-doc-export-paging-2018-07-31T09-09-29-120Z`
> FEATURE: RAIL-1016 Export executeAfm paging functions

- src/DataLayer/converters/MeasureConverter.ts
- src/DataLayer/converters/tests/MeasureConverter.spec.ts
- src/DataLayer/converters/tests/fixtures/MeasureConverter.visObj.fixtures.ts
- for operation change is in percent
> BB-1311: set default format for arithmetic m.

- src/gooddata.ts
- src/interfaces.ts
- src/report.ts
- src/util.ts
- src/xhr.ts
- test/report.test.ts
PR for [SD-150](https://jira.intgdc.com/browse/SD-150)
- Add new ReportModule and exportResult function
> FEATURE: SD-150 - Add new functions to adapt new APIs for exporting

- src/report.ts
- src/util.ts
- src/xhr.ts
PR for [SD-261](https://jira.intgdc.com/browse/SD-261)
- Fix export polling
- Add getHeaders into ApiResponse
- Add handleHeadPolling into utils
> RELATED: SD-261 - fix polling

- CHANGELOG.md
- src/project.ts
- test/helpers/execution.ts
- test/project.test.ts
added sdk.project.getConfig,
added sdk.project.getProjectFeatureFlags
---
> FEATURE: RAIL-1336 Gooddata-js support for project config endpoint

- CHANGELOG.md
_Description of changes (if multi-commit, short global summary & context;
if single-commit, feel free to leave empty)._
---
> TRIVIAL: Fix typo in changelog

- CHANGELOG.md
- package.json
- yarn.lock
> RELATED: RAIL-1531 upgrade typings

- CHANGELOG.md
- src/gooddata.ts
- src/referenceHandling.ts
- test/gooddata.test.ts
_Description of changes (if multi-commit, short global summary & context;
if single-commit, feel free to leave empty)._
---
> RELATED: ONE-3770 Export reference conversion utils

- CHANGELOG.md
- package.json
- yarn.lock
> RELATED: RAIL-1590 use ^ for dependencies

- .eslintrc
- .github/pull_request_template.md
- package.json
- yarn.lock
_Description of changes (if multi-commit, short global summary & context;
if single-commit, feel free to leave empty)._
---
> RELATED: FET-129 Remove unused eslint prettier

- src/constants/errors.ts
- src/report.ts
- test/report.test.ts
> BUGFIX: SD-502 update error status for export

- test/catalogue.test.ts
- test/execution/execute-afm.test.ts
- test/execution/experimental-executions.test.ts
- test/helpers/execution.ts
- test/helpers/headers.ts
- test/metadata.test.ts
- test/project.test.ts
- tslint.json
> RELATED: FET-232 tslint rule for lodash

- CHANGELOG.md
- src/DataLayer/converters/FilterConverter.ts
- src/execution/execute-afm.convert.ts
- src/interfaces.ts
- src/report.ts
- test/report.test.ts
---
- gooddata-react-components: https://github.com/gooddata/gooddata-react-components/pull/1080
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2352
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2125
- SD-530: https://jira.intgdc.com/browse/SD-530
> BUGFIX: SD-530 Can't export insight with filter by string

- package.json
- yarn.lock
> FEATURE: FET-319 Reformat source code with Prettier upon a commit

- CHANGELOG.md
- src/catalogue.ts
> RELATED: BB-1538 public ItemDescriptions loader

- CHANGELOG.md
- src/catalogue.ts
- src/interfaces.ts
- test/catalogue.test.ts
> RELATED: BB-1569 added itemDescriptionObjects api to catalogue

- CHANGELOG.md
- src/dashboard/dashboard.ts
- src/gooddata.ts
- src/report/report.ts
- src/utils/export.ts
- test/dashboard/dashboard.test.ts
- test/report/report.test.ts
- test/utils/export.test.ts
- yarn.lock
> FEATURE: SD-559 add exportDashboard function

- CHANGELOG.md
- package.json
- yarn.lock
> RELATED: RAIL-1719 use correct @gooddata/typings version

- CHANGELOG.md
- package.json
- yarn.lock
> RELATED: BB-1690 Use correct version of @gooddata/typings

- package.json
- src/interfaces.ts
- yarn.lock
Sync interface with real response to support "includeTotalCountWithoutFilters" option
---
https://github.com/gooddata/gooddata-react-components/pull/1182
> RELATED: ONE-4060 Extend interface to sync it with real response

- CHANGELOG.md
- src/DataLayer/utils/AfmUtils.ts
- src/DataLayer/utils/tests/AfmUtils.spec.ts
> RELATED: ONE-4103 Add util for "Select all" attribute filter

- package.json
- yarn.lock
> RELATED: FET-367 Add autofix copyright

- package.json
- src/DataLayer/fixtures/Afm.fixtures.ts
- src/DataLayer/utils/AfmUtils.ts
- src/DataLayer/utils/tests/AfmUtils.spec.ts
- yarn.lock
> gooddata-js RELATED: BB-1780 Measure value filters in AFM filter merging function

- src/user.ts
- test/user.test.ts
KD: https://github.com/gooddata/gdc-dashboards/pull/2423
---
> RELATED: SD-713 user config API

- CHANGELOG.md
- src/interfaces.ts
- src/report/report.ts
- src/xhr.ts
- test/report/__snapshots__/report.test.ts.snap
- test/report/report.fixtures.ts
- test/report/report.test.ts
- test/xhr.test.ts
Re-introducing the REST API version bump that will be released as MAJOR version `12.0.0`
---
> Re-intruduce REST API version bump

- src/execution/execute-afm.ts
- src/gooddata-browser.ts
- src/gooddata-node.ts
- src/typeGuards.ts
- test/execution/execute-afm.test.ts
> RELATED: ONE-4175 Store first-part of execution with error in data fetching

- CHANGELOG.md
- src/metadata.ts
- src/xhr.ts
- test/metadata.test.ts
- test/xhr.test.ts
> FEATURE: BB-1907 Add MVF support for getValidElements API

- CHANGELOG.md
> RELATED: BB-1907 Changelog fix

- .github/CODEOWNERS
> TRIVIAL: Change component owner

- yarn.lock
> TRIVIAL: upgrade devDependencies' transitive dependencies

- .github/pull_request_template.md
> TRIVIAL: extend PR template with release type info

- package.json
- src/metadataExt.ts
- src/user.ts
- test/fixtures/metadataExt.ts
- test/metadataExt.test.ts
- yarn.lock
> RELATED: RAIL-2044 Add typings and tests, RELATED: RAIL-2031 Add support for SPI SAML SSO

- .github/CODEOWNERS
> TRIVIAL: Remove PJA from codeowners as he has no time to code anymore

- CHANGELOG.md
- package.json
- yarn.lock
---
**Proposed release type:** patch
> RELATED: SD-884 upgrade typings

- src/bootstrap.ts
- src/gooddata.ts
- src/project.ts
- src/user.ts
- test/bootstrap.test.ts
---
**Proposed release type:** minor
Related ticket: https://jira.intgdc.com/browse/SD-936
GD-Labs: https://github.com/gooddata/gd-labs/pull/397
AD: https://github.com/gooddata/gdc-analytical-designer/pull/3063
KD: https://github.com/gooddata/gdc-dashboards/pull/2781
> RELATED: SD-936 add bootstrap module to fetch all data from resource

- docker/.config
- gdc_fossa.yaml
> FEATURE: FET-478 Add FOSSA configuration

- gdc_fossa.yaml
> RELATED: FET-478 Fix typo in the Fossa image path

- package.json
- yarn.lock
> RELATED: BB-2381 upgrade typings

- package.json
- yarn.lock
> RELATED: FET-484 Upgrade copyright-fix script

- CHANGELOG.md
- src/gooddata.ts
- src/ldm.ts
- test/ldm.test.ts
> RELATED: BB-2423 Add support for LDM getCommonAttribute

- CHANGELOG.md
- Gruntfile.js
- package.json
- yarn.lock
> RELATED: FET-474 Move grunt-grizzly under gooddata organization

- CHANGELOG.md
> BUGFIX: BB-2305 Remove temporary measure format override CHANGELOG

- pages/_layouts/api.html
- pages/_layouts/default.html
- pages/_layouts/post.html
- pages/css/bootstrap-responsive.css
- pages/css/bootstrap.css
- pages/css/style.css
- pages/getting-started/index.html
- pages/index.html
- src/bootstrap.ts
- tools/yuidoc/theme-gh-pages/assets/css/main.css
- tools/yuidoc/theme-gh-pages/assets/index.html
- tools/yuidoc/theme-gh-pages/assets/vendor/prettify/CHANGES.html
- tools/yuidoc/theme-gh-pages/assets/vendor/prettify/README.html
- tools/yuidoc/theme/assets/css/main.css
- tools/yuidoc/theme/assets/index.html
- tools/yuidoc/theme/assets/vendor/prettify/CHANGES.html
- tools/yuidoc/theme/assets/vendor/prettify/README.html
> RELATED: FET-563 Fix sonar-reported issues

- .sonar.settings
> RELATED: FET-564 Sonar config v2

- .travis.yml
> RELATED: FET-784 Remove travis from FE repositories

- LICENSE
- README.md
---
**Proposed release type:** patch (see points 6. - 8. of the [semver spec](https://semver.org/#semantic-versioning-specification-semver))
> RELATED: SETI-6387 update LICENSE file and README years

- docker/.config
> RELATED: FET-550 Use latest image

- sonar-project.properties
> INFRA-176: Add sonar-project.properties - cfg file for sonarcloud
