gooddata/gooddata-js

package.json
As of v1.2.20, npm throws annoying warning when there is no `"repository"` field present in the `package.json` file (try running `npm install`). This should fix it.
<3
=> Add 'repository' field to package.json to avoid npm warning

src/execution.js, test/execution_test.js
- we added headers transformation to simpleexecutor because correctly we would like to have attribute titles in axes not display form titles. But we have in columns only display forms so we added directly headers transformation to resource and return in attrLabel attribute title.
=> BUGFIX: CL-7896 Support headers in executionResult

package.json, src/execution.js, src/utils/rules.js
No hashing of items necessary. Lot of `partial` magic removed.
=> RELATED: CL-9573 Refactor sorting of metrics

src/execution.js, test/execution_test.js
Hi @vaclavbohac, @dprentis 
this PR is changing how `orderBy` part of execution payload is created:
1. sort is not happening on generated columns (eg on PoP column) but on column/values for which the generated column was created (measure wit showPoP flag set to true)
2. sorting on generated columns is now not possible (would need changes in MD or accept values other than `asc' or 'desc')
this change is needed for [CL-9038](https://jira.intgdc.com/browse/CL-9038?filter=-3)
Petr
=> RELATED: CL-9038 use measure column instead of generated PoP column for sorting

src/catalogue.js, test/catalogue_test.js
- we need this because e.g. 'PoP' metric with 'Show in %' could be compoused from 3 particular metrics and when we replace in 'PoP' expression 'Show in %' identifier we need to replace also possible identifiers in this ('Show in %') expression, etc.
=> BUGFIX: CL-10197 Replace identifiers in MAQL recursively

src/execution.js, test/execution_test.js
Filters are no longer assigned to a map on the basis of their
displayForm uri and all attribute filters are passed to backend in an
$and clause. This way, we keep backend to combine filter values when
it's already implemented there.
Specification: https://docs.google.com/presentation/d/1n2GA3vU7MagTODxWyxxaowG3fP9m3v6rNhp6xMxcHdw/edit#slide=id.g113d5c850e_0_0
=> RELATED: ONE-1993 Wrap filters in "$and" to support multiple filters of same type

src/execution.js, test/execution_test.js
The public Javascript SDK uses the experimental/executions API that can provide results in two forms:
- Tabular form with attribute and metric values
- Extended tabular form that also includes the internal attribute element IDs
Unfortunately, the SDK always returns data in the tabular form. This PR adds the `extended` option to the `executions.getData` function makes the `getData` function to return data in the extended format.
The internal attribute element IDs are useful when you want to use the retrieve results to generate a filter for subsequent execution requests.
=> FEATURE: CL-10935 Enable extended report execution results

package.json
=> TRIVIAL: Remove module from package.json

src/execution.js, test/execution_test.js
Make sure we call execution resource with numbers, no matter if relative
dateFilter has from/to stored as strings or numbers.
=> RELATED: ONE-2627 Allow relative dateFilter from/to to be passed as strings

src/DataLayer/converters/MeasureConverter.ts, src/DataLayer/converters/tests/MeasureConverter.spec.ts, src/DataLayer/converters/tests/fixtures/Afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/MeasureConverter.afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/MeasureConverter.visObj.fixtures.ts, src/DataLayer/converters/tests/toAfmResultSpec.spec.ts
`8.1.1-ocetnik-doc-measure-format-2018-09-19T13-29-51-263Z`
=> RELATED: RAIL-1118 Propagate requested measure format from visualizationObject to AFM

CHANGELOG.md, src/DataLayer/converters/tests/fixtures/Afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/VisObj.fixtures.ts, src/DataLayer/converters/tests/toAfmResultSpec.spec.ts, src/DataLayer/converters/toAfmResultSpec.ts
Native totals now convert just to empty attributeIdentifiers. We want to specify nativeTotal for other than first attribute.
```
execution.afm.nativeTotals: [
{attributeIdentifiers: [], measureIdentifier: 'm1'},           // grand total
{attributeIdentifiers: ['a1'], measureIdentifier: 'm1'},       // subtotal 1
{attributeIdentifiers: ['a1', 'a2'], measureIdentifier: 'm1'}, // subtotal 2
]
```
---
=> RELATED: BB-1406 convert subtotals to nativetotals

CHANGELOG.md, package.json, yarn.lock
_Description of changes (if multi-commit, short global summary & context;
if single-commit, feel free to leave empty)._
---
- N/A
- done
- N/A
=> RELATED: ONE-3511 Bump `@gooddata/typings` from 2.7.1 to 2.8.0

CHANGELOG.md, jest.ci.json, package.json, src/DataLayer/converters/FilterConverter.ts, src/DataLayer/converters/MeasureConverter.ts, src/DataLayer/converters/tests/FilterConverter.spec.ts, src/DataLayer/converters/tests/fixtures/FilterConverter.afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/FilterConverter.input.fixtures.ts, src/DataLayer/converters/toAfmResultSpec.ts, src/DataLayer/helpers/filters.ts, src/DataLayer/helpers/tests/filters.input.fixtures.ts, src/DataLayer/helpers/tests/filters.spec.ts, src/DataLayer/utils/AfmUtils.ts, src/execution/execute-afm.convert.ts, src/execution/execute-afm.ts, src/execution/tests/execute-afm.convert.spec.ts, src/execution/tests/fixtures.ts, src/metadata.ts, yarn.lock
Multiple changes:
- Refactor / cleanup and consolidation of AFM > Vis Object conversions (remove duplicated code, filter conversion in separate source file, more tests)
- Refator / sanitization in helpers/filters.ts- added code comments, deprecated nonsense method, removed duplicate date filter type guard
- Refactor / cleanup in AfmUtils - removed duplicate filter-related type guard implementations; those that were exported remain in code but are marked as deprecated and merely delegate to guards in typings
- Updated execution-afm & metadata.ts  - add conversion from AFM types to ExecuteAFM types before payload is sent to executeAFm endpoint
---
- ~~[ ] Migration guide (for major update) is written to [CHANGELOG.md](../blob/master/CHANGELOG.md).~~
=> FEATURE: ONE-3610 Support for text filters in GoodData.UI

CHANGELOG.md, package.json, src/DataLayer/converters/tests/MeasureConverter.spec.ts, src/DataLayer/converters/tests/fixtures/Afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/MeasureConverter.afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/MeasureConverter.visObj.fixtures.ts, src/DataLayer/converters/tests/fixtures/VisObj.fixtures.ts, src/DataLayer/converters/tests/toAfmResultSpec.spec.ts, src/execution/execute-afm.convert.ts, src/execution/tests/execute-afm.convert.spec.ts, src/execution/tests/fixtures.ts, yarn.lock
This PR completes previously started work on text filters:
- It ensures that simple measures have their filters correctly transformed from AFM to ExecuteAFM format, reflecting the definition of textFilter value
---
=> RELATED: ONE-3610 Support text filters in simple measures

CHANGELOG.md, src/interfaces.ts, src/report.ts, src/util.ts, test/helpers/polling.ts, test/report.test.ts, test/util.test.ts
PR for [SD-303](https://jira.intgdc.com/browse/SD-303)
- Distinguishes between common error and restricted error message.
- Add showFilters parameter into ExportConfig interface [SD-465](https://jira.intgdc.com/browse/SD-465)
---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2264
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2007
=> BUGFIX: SD-303, FEATURE: SD-465

.travis.yml, src/execution.ts, src/execution/execute-afm.ts
This PR delivers minimum infrastructure needed to support experimental data sources that use the `executeVisualization` backend instead of `executeAfm` when rendering visualization by URI:
ExecuteVisualization backend allows to pass URI + filters + resultSpec; given these, it automatically constructs AFM and calls the executeAfm logic; the execution response and results and everything else from that point on remains the same as with executeAfm. Code related to fiddling with the results can be thus reused as-is.
- ExecuteAfmModule now contains _executeVisualization and _getVisExecutionResponse methods
- The new methods will be 'annotated' and documented as experimental and not part of the gooddata-js public API just yet
The newly introduced methods will be made public once we adopt their …
=> RELATED: ONE-3955 Experimental support of executeVisualization

CHANGELOG.md, src/DataLayer/adapters/ExecuteAfmAdapter.ts
We need to be able to change it ex post in some cases.
=> RELATED: RAIL-1719 make adapters projectId public

CHANGELOG.md, src/DataLayer/converters/FilterConverter.ts, src/DataLayer/converters/tests/FilterConverter.spec.ts, src/DataLayer/converters/tests/fixtures/Afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/FilterConverter.afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/FilterConverter.input.fixtures.ts, src/DataLayer/converters/tests/fixtures/VisObj.fixtures.ts, src/DataLayer/converters/tests/toAfmResultSpec.spec.ts, src/DataLayer/converters/toAfmResultSpec.ts, src/execution/tests/execute-afm.convert.spec.ts, src/execution/tests/fixtures.ts, yarn.lock
=> RELATED: BB-1690 Support measure value filters in UI SDK

src/report/report.ts, test/report/__snapshots__/report.test.ts.snap, test/report/report.fixtures.ts, test/report/report.test.ts
The conversion from AFM to ExecuteAFM type was missing. It was possible to send filter format unsupported by the REST API, for example, "textFilter: true" was send instead of "values: [...attributeElementValues]". AFM in the export config is correctly sanitized now.
---
=> RELATED: BB-1885: Sanitize exported AFM filters

src/DataLayer/constants/buckets.ts, src/DataLayer/converters/model/VisualizationObject.ts, src/DataLayer/converters/tests/fixtures/VisObj.fixtures.ts, src/DataLayer/converters/tests/toAfmResultSpec.spec.ts, src/DataLayer/converters/toAfmResultSpec.ts
=> FEATURE: SD-769 save/load geo pushpin

src/DataLayer/constants/buckets.ts, src/DataLayer/converters/tests/fixtures/VisObj.fixtures.ts, src/DataLayer/converters/tests/toAfmResultSpec.spec.ts, src/DataLayer/converters/toAfmResultSpec.ts
---
**Proposed release type:** patch
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2874
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2613
- SD-825: https://jira.intgdc.com/browse/SD-825
=> BUGFIX: SD-825 Attribute name in tooltip isn't updated after renaming

CHANGELOG.md, src/metadataExt.ts
**Proposed release type:** patch
(https://semver.org/#semantic-versioning-specification-semver))
- gdc-dashboards:  https://github.com/gooddata/gdc-dashboards/pull/2649
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2926
=> BUGFIX: RAIL-2138, RAIL-2131 Fix saveAs button problem with old dashboards without layout and update date in meta

CHANGELOG.md, src/DataLayer/converters/MeasureConverter.ts, src/DataLayer/converters/tests/MeasureConverter.spec.ts, src/DataLayer/converters/tests/fixtures/MeasureConverter.afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/MeasureConverter.visObj.fixtures.ts
toAfmResultSpec is adding default formats to attribute-based measures(whole number), show in % measures(percentage) and arithmetic measures with operator change(percentage) It was preferring these default formats over formats from the provided visualization object which is fixed by this PR. 
Note that for fact-based measures the default format is not generated which is strange but not fixed by this PR
---
=> FEATURE: BB-2259 Respect custom measure format in toAfmResultSpec

src/DataLayer/constants/formats.ts, src/DataLayer/converters/MeasureConverter.ts, src/DataLayer/converters/tests/MeasureConverter.spec.ts, src/DataLayer/converters/tests/fixtures/MeasureConverter.afm.fixtures.ts, src/DataLayer/converters/tests/fixtures/MeasureConverter.visObj.fixtures.ts
=> BUGFIX: BB-2286 Override default format of ad-hoc % measures

package.json, src/gooddata.ts, src/metadata.ts, src/referenceHandling.ts, test/metadata.test.ts, yarn.lock
Extend handling of properties+references to the VisualizationWidget
---
=> RELATED: ONE-4414 Support for properties in Widget MD object

CHANGELOG.md, src/metadataExt.ts
Add new optional attribute, `summary`,  to metadataExt.saveDashboard `options` param
---
**Proposed release type:** minor
(see points 6. - 8. of the [semver spec](https://semver.org/#semantic-versioning-specification-semver))
=> Add summary to save dashboard as

src/DataLayer/converters/MeasureConverter.ts, src/DataLayer/converters/tests/MeasureConverter.spec.ts
When implementing custom measure format we found out that some measures have incorrect format saved in metadata object. As we started to respect the format saved in viz. object the measures would be formatted wrongly so we introduced this fix for them. In https://jira.intgdc.com/browse/MDC-217 these measures have been fixed so that the override is not needed any more 
---
=> BUGFIX: BB-2305 Remove temporary measure format override

CHANGELOG.md, src/metadataExt.ts
This allows the users without admin privileges to duplicate locked items.
Implemented as opt-in to maintain backwards compatibility.
---
**Proposed release type:** minor (see points 6. - 8. of the [semver spec](https://semver.org/#semantic-versioning-specification-semver))
=> RELATED: RAIL-2860 Add clearLockedFlag option to saveDashboardAs
